<?php

declare(strict_types=1);

return [
    'name' => 'KodaKodra',
    'short_name' => 'KodaKodra',
    'title' => 'Software Engineer & Web Developer',
    'tagline' => 'Full-stack web development, software engineering and bespoke digital projects.',
    'description' => 'Portfolio of full-stack web development, software engineering and bespoke digital projects by KodaKodra.',
    'site_url' => env('SITE_URL', 'http://localhost:8000'),
    'locale' => 'en_GB',
    'email' => env('CONTACT_EMAIL', 'hello@example.com'),
    'location' => 'United Kingdom',
    'availability' => 'Available for selected freelance and contract work.',
    'cv_url' => '',
    'primary_action' => ['label' => 'View projects', 'href' => '/projects'],
    'secondary_action' => ['label' => 'Get in touch', 'href' => '/contact'],
    'navigation' => [
        ['label' => 'Home', 'href' => '/'],
        ['label' => 'Projects', 'href' => '/projects'],
        ['label' => 'About', 'href' => '/about'],
        ['label' => 'Contact', 'href' => '/contact'],
    ],
    'theme' => [
        'brand' => '#162033',
        'brand_dark' => '#0d1422',
        'accent' => '#5ea6ff',
        'surface' => '#f5f7fb',
        'surface_alt' => '#eaf0f8',
        'text' => '#18202d',
        'muted' => '#5a6677',
    ],
    'hero' => [
        'eyebrow' => 'Full-stack web developer · Software engineer',
        'title' => 'Building practical software and thoughtful digital experiences.',
        'body' => 'Solo full-stack developer with 8 years of professional backend and engineering experience, building Laravel and React applications end-to-end across scoping, database design, development, testing and deployment.',
        'points' => [
            'Bespoke applications and websites built from scratch',
            'Refactoring, QA, regression testing and problem solving',
            'Development, product and data decisions within a project',
        ],
    ],
    'intro' => [
        'eyebrow' => 'Selected work',
        'title' => 'Projects across web, software and digital products.',
        'body' => 'A selection of software, web development and product work covering custom applications, public-facing websites, data-driven systems and ongoing engineering work.',
    ],
    'projects' => [
        [
            'slug' => 'kodakodra-social',
            'title' => 'KodaKodraSocial',
            'category' => 'Laravel · Social platform',
            'summary' => 'A solo-built social media platform developed from scratch with core platform functionality.',
            'description' => 'A full-stack Laravel application covering authentication, user profiles, social interactions, content management and other core platform functionality. Built independently from the ground up with the application architecture and feature set developed end-to-end.',
            'stack' => ['Laravel', 'PHP', 'JavaScript', 'SQL'],
            'highlights' => ['Authentication and user profiles', 'Social interactions and content management', 'End-to-end solo development'],
            'url' => 'https://github.com/kodakodra',
            'status' => 'Selected project',
        ],
        [
            'slug' => 'torin',
            'title' => 'Torin',
            'category' => 'Java · LWJGL · OpenGL',
            'summary' => 'A voxel game engine project built from scratch with procedural worlds, rendering, physics and celestial systems.',
            'description' => 'A personal voxel-engine project built from scratch using Java, LWJGL, OpenGL and Gradle. Work includes procedural world generation, chunk-based rendering, physics, block interaction, dynamic lighting, entities and a day/night celestial system.',
            'stack' => ['Java', 'LWJGL', 'OpenGL', 'Gradle', 'JOML'],
            'highlights' => ['Procedural world generation and chunk rendering', 'Physics, entities and block interaction', 'Dynamic lighting and celestial cycle'],
            'url' => 'https://github.com/kodakodra/Torin',
            'status' => 'In development',
        ],
        [
            'slug' => 'ecommerce-booking-platforms',
            'title' => 'E-commerce & Booking Platforms',
            'category' => 'Full-stack web development',
            'summary' => 'Bespoke e-commerce and booking solutions with customer-facing interfaces and supporting backend systems.',
            'description' => 'Developed and maintained bespoke e-commerce and booking solutions covering customer-facing interfaces, administration functionality, product and service management, booking workflows and supporting backend systems.',
            'stack' => ['PHP', 'Laravel', 'JavaScript', 'SQL'],
            'highlights' => ['Customer-facing interfaces and workflows', 'Product and service management', 'Booking and supporting backend systems'],
            'url' => '',
            'status' => 'Selected work',
        ],
        [
            'slug' => 'dashboards-analytics',
            'title' => 'Business Dashboards & Analytics',
            'category' => 'Data-driven web applications',
            'summary' => 'Bespoke dashboards and analytics interfaces for presenting operational and business data clearly.',
            'description' => 'Built bespoke dashboards and analytics interfaces for presenting operational and business data, with a focus on usability, efficiency and clear information presentation.',
            'stack' => ['PHP', 'JavaScript', 'SQL', 'HTML', 'CSS'],
            'highlights' => ['Operational and business data presentation', 'Usability and information clarity', 'Bespoke interfaces built around requirements'],
            'url' => '',
            'status' => 'Selected work',
        ],
        [
            'slug' => 'websites-digital-platforms',
            'title' => 'Websites & Digital Platforms',
            'category' => 'Bespoke development',
            'summary' => 'Websites and web applications spanning portfolios, brochure sites and bespoke small-business platforms.',
            'description' => 'Delivered websites and web applications ranging from portfolios and brochure sites to bespoke small-business platforms, developing solutions from scratch and adapting existing systems to specific requirements.',
            'stack' => ['PHP', 'JavaScript', 'HTML5', 'CSS3'],
            'highlights' => ['Custom websites and web applications', 'From-scratch builds and tailored adaptations', 'Small-business and client-focused platforms'],
            'url' => '',
            'status' => 'Selected work',
        ],
        [
            'slug' => 'legacy-systems-qa',
            'title' => 'Legacy Systems & QA',
            'category' => 'Maintenance · Refactoring · Testing',
            'summary' => 'Maintenance and improvement work across existing applications, including bug fixing, refactoring and regression testing.',
            'description' => 'Worked across existing applications to diagnose and resolve bugs, refactor inefficient code and improve reliability through QA, regression testing, planning and workflow optimisation.',
            'stack' => ['PHP', 'Laravel', 'Pest', 'PHPUnit', 'PHPStan'],
            'highlights' => ['Bug diagnosis and resolution', 'Refactoring and maintainability improvements', 'QA and regression testing'],
            'url' => '',
            'status' => 'Selected work',
        ],
        [
            'slug' => 'business-site',
            'title' => 'Business Site',
            'category' => 'PHP · Web development',
            'summary' => 'A reusable production-minded PHP brochure-site foundation for service businesses and professional firms.',
            'description' => 'A configuration-driven PHP project covering responsive pages, secure contact handling, PHPMailer SMTP delivery, SEO foundations, legal pages, tests, documentation and deployment guidance.',
            'stack' => ['PHP 8.2+', 'Composer', 'PHPMailer', 'Apache'],
            'highlights' => ['Secure contact forms and SMTP email', 'SEO, accessibility and deployment foundations', 'Reusable configuration-driven architecture'],
            'url' => 'https://github.com/kodakodra/business-site',
            'status' => 'Complete',
        ],
    ],
    'skills' => [
        ['group' => 'Languages', 'items' => ['PHP', 'JavaScript', 'TypeScript', 'Java', 'SQL', 'VBA', 'HTML5', 'CSS3']],
        ['group' => 'Backend & frameworks', 'items' => ['Laravel', 'Node.js', 'RESTful APIs', 'Blade', 'PHPUnit', 'Pest']],
        ['group' => 'Frontend & graphics', 'items' => ['React', 'Blade', 'jQuery', 'Bootstrap 5', 'LWJGL', 'OpenGL']],
        ['group' => 'Databases', 'items' => ['MariaDB', 'MySQL', 'PostgreSQL', 'Redis', 'phpMyAdmin', 'HeidiSQL', 'DBeaver']],
        ['group' => 'Tooling & environment', 'items' => ['Git', 'GitHub', 'Docker', 'Docker Compose', 'Composer', 'npm', 'Gradle', 'Apache', 'Bash', 'JSON', 'YAML', 'Markdown']],
        ['group' => 'Testing & quality', 'items' => ['Pest', 'PHPUnit', 'Nightwatch', 'PHPStan', 'QA testing', 'Regression testing']],
        ['group' => 'Professional skills', 'items' => ['Customer service', 'Complaint & query resolution', 'Team leadership', 'Problem-solving', 'Working under pressure']],
    ],
    'experience' => [
        [
            'period' => '2019 – Present',
            'title' => 'Web Developer — Independent / Solo Projects',
            'body' => 'Design and build web applications independently across social networks, e-commerce, portfolios, brochure sites, dashboards and analytics tools, booking systems and small-business sites, primarily using Laravel and PHP alongside React and TypeScript.',
        ],
        [
            'period' => '2019 – Present',
            'title' => 'End-to-end engineering & delivery',
            'body' => 'Own projects across scoping, database design, development, testing and deployment. Cover authentication, search, messaging, notifications, payments, content management, booking systems, dashboards and analytics, alongside planning, efficiency and product tracking work.',
        ],
        [
            'period' => '2019 – Present',
            'title' => 'Maintenance, QA & collaboration',
            'body' => 'Maintain and improve existing systems through refactoring, bug fixing, QA and regression testing. Collaborate with other developers on GitHub through pull requests, code review and shared repositories where projects require it.',
        ],
        [
            'period' => '1998 – 2018',
            'title' => 'Customer Service & Team Support — Retail & Hospitality',
            'body' => 'Two decades of frontline customer service across supermarket, food service and retail settings, handling queries, complaints, transactions and shift cover during busy periods.',
        ],
        [
            'period' => '2018 – 2019',
            'title' => 'Career break',
            'body' => 'Career break for full-time family caring responsibilities, followed by a deliberate move toward technical and project-based work.',
        ],
    ],
    'education' => [
        ['period' => '2022', 'title' => 'Team Leading & Management', 'body' => 'NCFE Level 2 & 3'],
        ['period' => '2004', 'title' => 'Information & Communication Technology', 'body' => 'AVCE Level 3'],
        ['period' => '2003', 'title' => 'GCSEs', 'body' => 'English, Mathematics, IT and 3× Sciences (A–C)'],
    ],
    'about' => [
        'eyebrow' => 'About',
        'title' => 'A practical engineering approach from idea to delivery.',
        'body' => 'A solo full-stack web developer with professional backend and engineering experience, comfortable covering development, product and data decisions within a project rather than working from a narrow brief. Earlier frontline customer-service experience also brings a strong focus on clear communication, reliability and problem-solving under pressure.',
    ],
    'process' => [
        ['number' => '01', 'title' => 'Scope', 'body' => 'Understand the problem, requirements, constraints and useful outcome before implementation begins.'],
        ['number' => '02', 'title' => 'Build', 'body' => 'Design the data and application structure, then develop the required features end-to-end.'],
        ['number' => '03', 'title' => 'Test', 'body' => 'Verify behaviour, diagnose defects and regression-test important paths before delivery.'],
        ['number' => '04', 'title' => 'Refine', 'body' => 'Improve usability, maintainability, efficiency and documentation as the project develops.'],
    ],
    'social' => [
        ['label' => 'GitHub', 'href' => 'https://github.com/kodakodra'],
        ['label' => 'Portfolio', 'href' => 'https://kodakodra.github.io'],
        ['label' => 'LinkedIn', 'href' => 'https://www.linkedin.com/'],
    ],
    'legal' => [
        'privacy_contact' => env('CONTACT_EMAIL', 'hello@example.com'),
        'owner_notice' => 'Replace with your preferred legal or business details where applicable.',
    ],
];
